const colour = {
	black: ["albino", "arctic", "ashen", "aspen", "aufeis", "augur", "basalt", "birch", "black", "bluepoinsettia", 
			"cairngorm", "celestial", "celsian", "chartreux", "chestnut", "cimmerian", "clearwhite", "cloudburst", 
			"cocoa", "constellation", "cottoncandy", "dapplegray", "darkbrown", "demiurge", "desolate", "dikela", 
			"divine", "dovegray", "duat", "dun", "dusty", "ebony", "eggshell", "elysian", "ennead", "flint", 
			"frost", "frostbitten", "glacial", "glass", "gleam", "gray", "gunmetalgray", "harbinger", "haruspex", 
			"haze", "heh", "hematite", "hoarfrost", "ice", "incense", "incorporeal", "interstellar", "isabel", 
			"jellyfish", "jet", "khnum", "korat", "kunzite", "leonid", "lilac", "liver", "majivu", "maltese", 
			"medal", "mistletoe", "moonstone", "murk", "nadir", "nephthys", "noctis", "nun", "nuummite", "obsidian", 
			"onyx", "opal", "opalescent", "penumbra", "pewter", "phantom", "platinum", "pulsar", "ra", "rhino", 
			"rime", "rosybrown", "shard", "sidereal", "silver", "silvergray", "skyward", "slate", "snowflake", 
			"snowpard", "soul", "spectre", "steele", "sterling", "stratosphere", "styx", "titanium", "vandal", 
			"velvet", "waterhyacinth", "white", "willow", "witch", "zombie"],
	cream: ["aardwolf", "aether", "alabaster", "almond", "amber", "ammonite", "antler", "apricot", "arabica", 
			"argent", "asiatic", "atlas", "beige", "blonde", "buff", "buttercream", "buttermilk", "butternut", 
			"camel", "cameo", "caramel", "cherryblossom", "citron", "cream", "creamdarker", "creamlighter", 
			"darkfawn", "darkvanilla", "deepfawn", "dustyrose", "eggnog", "esker", "ethereal", "fawn", "finch", 
			"flaxen", "fossil", "grullo", "guardian", "hallowed", "hazelnut", "heavenly", "hellebore", "horizon", 
			"howlite", "inpu", "ivory", "jacana", "jackal", "khaki", "latte", "lightcream", "meteorite", "mongoose", 
			"mossagate", "mummy", "mushroom", "nacre", "nautilus", "nomad", "olive", "outlaw", "parhelion", "pearl", 
			"pecan", "pecora", "persimmon", "przewalski", "qahir", "ragdoll", "reindeer", "ruffian", "russet", 
			"savannah", "seer", "senegal", "skeletal", "smog", "solaris", "soot", "sphinx", "supernal", "tan", 
			"teardrop", "thoth", "tusk", "vagabond", "vanilla"],
	golden: ["abyssinian", "ailurus", "angelic", "anubis", "asali", "bast", "bisque", "bisquit", "bone", "bushveld", 
			 "cabochon", "champagne", "chatoyant", "citrine", "cretaceous", "damu", "dandelion", "darkgolden", "deira",
			 "dhahabi", "dinar", "doubloon", "ducat", "ember", "festive", "fulvous", "ganache", "gilded", "goldenrod", 
			 "goridhe", "green", "gregarious", "haliotis", "harvestmoon", "hexaplex", "hirola", "honey", "horus", 
			 "hyena", "jacinthe", "kimanjano", "labradorite", "lemon", "lightgolden", "linen", "luteo", "maat", 
			 "mandarin", "marula", "maziwa", "mediumgolden", "mobola", "mudstone", "nacarat", "nudar", "oatmeal", 
			 "ochre", "ornament", "peach", "powder", "protostar", "ripe", "saffron", "sahara", "sarcophagus", 
			 "sepulture", "sulphur", "sundust", "sunflower", "sunglow", "sunkissed", "sunshine", "sunspot", "swarm", 
			 "topaz", "triumph", "trophy", "udara", "ukame", "victor", "wheaten", "wither", "xanthic", "zarafshan", 
			 "zarasa", "zarbanu", "zarin", "zer", "zivar", "zloto"],
	red: ["auburn", "brass", "bronze", "mulberry", "ruddy", "cassis", "prune", "ambrosia", "ater", "beet", "demonic", 
		  "haunted", "madagascar", "nether", "rhodonite", "roughruby", "temporal", "unholy", "wepwawet", "ginger", 
		  "mauve", "rust", "rhubarb", "anjeer", "scallop", "ankh", "brimstone", "chaos", "deshret", "hibiscus", 
		  "inferno", "ogdoad", "progenitor", "scoundrel", "squall", "sunset", "wine", "copper", "palomino", "sorrel", 
		  "tawny", "rufous", "fiery", "maroon", "taupe", "ancestral", "astral", "azalea", "bandit", "blazing", "dawn", 
		  "drupa", "flamingo", "fuchsia", "iris", "lotus", "nefer", "sunrise", "sutekh", "chocolate", "henna", 
		  "redwood", "acacia", "shedua", "blackrose", "bloodmoon", "bloodbourne", "bloodstone", "manakbir", "manticore", 
		  "merlot", "plague", "prismatic", "sha", "wicked", "brown", "locust", "mahogany", "sienna", "red", "umber", 
		  "blushrose", "protea", "rosegold", "sepia", "seth", "windfall", "cedar", "cremello", "fallow", "sandy", 
		  "wildrose", "cinnabar", "sapela", "ardor", "decennial","orchid", "rainbow", "rosepink", "serruria", "ubaste"],
}

const gradient = {
	solid: ["acacia", "alabaster", "albino", "amber", "apricot", "ardor", "argent", "ashen", "aspen", "atlas", "basalt", 
			"beige", "birch", "bisque", "blackrose", "bloodbourne", "bloodmoon", "bloodstone", "blushrose", "brown", 
			"buttercream", "buttermilk", "butternut", "cairngorm", "camel", "caramel", "cedar", "celsian", "chatoyant", 
			"chestnut", "chocolate", "cinnabar", "citron", "clearwhite", "cream", "creamdarker", "creamlighter", 
			"cremello", "damu", "dandelion", "dapplegray", "darkbrown", "darkfawn", "darkgolden", "decennial", 
			"demiurge", "duat", "ebony", "eggshell", "fallow", "fawn", "festive", "flint", "frost", "frostbitten", 
			"gilded", "glass", "gleam", "goldenrod", "green", "gregarious", "harbinger", "haruspex", "harvestmoon", 
			"haze", "heavenly", "heh", "hellebore", "henna", "hexaplex", "honey", "incense", "incorporeal", 
			"interstellar", "isabel", "jet", "khaki", "khnum", "labradorite", "latte", "lemon", "lightcream", 
			"lightgolden", "lilac", "linen", "liver", "locust", "luteo", "mahogany", "majivu", "manakbir", "manticore", 
			"marula", "medal", "mediumgolden", "merlot", "meteorite", "mobola", "mudstone", "nadir", "nephthys", 
			"noctis", "nun", "nuummite", "obsidian", "onyx", "opalescent", "orchid", "ornament", "parhelion", "pearl", 
			"persimmon", "phantom", "plague", "platinum", "prismatic", "protea", "protostar", "przewalski", "qahir", 
			"rainbow", "red", "redwood", "rhino", "rosegold", "rosepink", "ruffian", "sahara", "sandy", "sapela", 
			"sarcophagus", "seer", "sepia", "serruria", "seth", "sha", "shedua", "sienna", "silver", "solaris", "soot", 
			"spectre", "sphinx", "styx", "sulphur","sundust", "sunkissed", "sunshine", "tan", "teardrop", "titanium", 
			"topaz", "trophy", "ubaste", "udara", "ukame", "umber", "velvet", "victor", "waterhyacinth", "white", 
			"wicked", "wildrose", "willow", "windfall", "xanthic", "zarafshan", "zarasa", "zarbanu", "zarin", "zer", 
			"zivar"],
	countershade: ["aardwolf", "abyssinian", "aether", "ailurus", "almond", "ambrosia", "ammonite", "ancestral", 
				   "angelic", "anjeer", "ankh", "antler", "anubis", "arabica", "arctic", "asali", "asiatic", "astral", 
				   "ater", "auburn","aufeis", "augur", "azalea", "bandit", "bast", "beet", "bisquit", "black", 
				   "blazing", "blonde", "bluepoinsettia", "bone", "brass", "brimstone", "bronze", "buff", "bushveld", 
				   "cabochon", "cameo", "cassis", "celestial", "champagne", "chaos", "chartreux", "cherryblossom", 
				   "cimmerian", "citrine", "cloudburst", "cocoa", "constellation", "copper", "cottoncandy", "cretaceous", 
				   "darkvanilla", "dawn", "deepfawn", "deira", "demonic", "deshret", "desolate", "dhahabi", "dikela", 
				   "dinar", "divine", "doubloon", "dovegray", "drupa", "ducat", "dun", "dusty", "dustyrose", "eggnog", 
				   "elysian", "ember", "ennead", "esker","ethereal", "fiery", "finch", "flamingo", "flaxen", "fossil", 
				   "fuchsia", "fulvous", "ganache", "ginger", "glacial", "goridhe", "gray", "grullo", "guardian", 
				   "gunmetalgray", "haliotis", "hallowed", "haunted", "hazelnut", "hematite", "hibiscus", "hirola", 
				   "hoarfrost", "horizon", "horus", "howlite", "hyena", "ice", "inferno", "inpu", "iris", "ivory", 
				   "jacana", "jacinthe", "jackal", "jellyfish", "kimanjano", "korat", "kunzite", "leonid", "lotus", 
				   "maat", "madagascar", "maltese", "mandarin", "maroon", "mauve", "maziwa", "mistletoe", "mongoose", 
				   "moonstone", "mossagate", "mulberry", "mummy", "murk", "mushroom", "nacarat","nacre", "nautilus", 
				   "nefer", "nether", "nomad", "nudar", "oatmeal", "ochre", "ogdoad", "olive", "opal", "outlaw", 
				   "palomino", "peach", "pecan", "pecora", "penumbra", "pewter", "powder", "progenitor", "prune", "pulsar", 
				   "ra", "ragdoll", "reindeer", "rhodonite", "rhubarb", "rime", "ripe", "rosybrown", "roughruby", "ruddy", 
				   "rufous", "russet", "rust", "saffron", "savannah", "scallop", "scoundrel", "senegal", "sepulture", 
				   "shard", "sidereal", "silvergray", "skeletal", "skyward", "slate", "smog", "snowflake", "snowpard", 
				   "sorrel", "soul", "squall", "steele", "sterling", "stratosphere", "sunflower", "sunglow", "sunrise", 
				   "sunset", "sunspot", "supernal", "sutekh", "swarm", "taupe", "tawny", "temporal", "thoth", "triumph", 
				   "tusk", "unholy", "vagabond", "vandal", "vanilla", "wepwawet", "wheaten", "wine", "witch", "wither", 
				   "zloto", "zombie"],
}

const shade = {
	dark: ["black", "dikela", "gray", "pewter", "vandal", "gunmetalgray", "korat", "cimmerian", "slate", "augur", 
		   "celestial", "constellation", "divine", "elysian", "ice", "jellyfish", "penumbra", "ra", "shard", "witch", 
		   "chestnut", "jet", "obsidian", "titanium", "onyx", "ebony", "noctis", "harbinger", "haruspex", "haze", "heh", 
		   "incense", "interstellar", "nadir", "nun", "nuummite", "spectre", "styx", "velvet", "blonde", "dustyrose", 
		   "pecan", "savannah", "russet", "flaxen", "senegal", "arabica", "grullo", "inpu", "jacana", "mossagate", "mummy", 
		   "nacre", "nomad", "olive", "outlaw", "reindeer", "supernal", "thoth", "vagabond", "caramel", "khaki", 
		   "persimmon", "tan", "butternut", "amber", "soot", "hellebore", "meteorite", "parhelion", "przewalski", "qahir",
		   "seer", "deira", "doubloon", "jacinthe", "ochre", "dinar", "fulvous", "abyssinian", "anubis", "asali",
		   "cretaceous", "ember", "ganache", "hyena", "kimanjano", "ripe", "swarm", "darkgolden", "zarafshan", "zarbanu", 
		   "xanthic", "honey", "udara", "chatoyant", "damu", "mudstone", "ornament", "protostar", "sarcophagus", "trophy", 
		   "auburn", "brass", "bronze", "mulberry", "ruddy", "cassis", "prune", "ambrosia", "ater", "beet", "demonic", 
		   "haunted", "madagascar", "nether", "rhodonite", "roughruby", "temporal", "unholy", "wepwawet", "chocolate", 
		   "henna", "redwood", "acacia", "shedua", "blackrose", "bloodmoon", "bloodbourne", "bloodstone", "manakbir",
		   "manticore", "merlot", "plague", "prismatic", "sha", "wicked"],
	medium: ["brown", "locust", "mahogany", "sienna", "red", "umber", "blushrose", "protea", "rosegold", "sepia", "seth", 
			 "windfall", "ginger", "mauve", "rust", "rhubarb", "anjeer", "scallop", "ankh", "brimstone", "chaos", 
			 "deshret", "hibiscus", "inferno", "ogdoad", "progenitor", "scoundrel", "squall", "sunset", "wine", "luteo", 
			 "mediumgolden", "sundust", "zarasa", "zarin", "topaz", "dandelion", "goldenrod", "gilded", "green", 
			 "gregarious", "labradorite", "mobola", "sahara", "victor", "ducat", "oatmeal", "saffron", "sunflower", 
			 "goridhe", "nacarat", "ailurus", "bast", "bushveld", "cabochon", "dhahabi", "hirola", "mandarin", "maziwa", 
			 "sepulture", "sunspot", "wither", "zloto", "camel", "cream", "creamdarker", "darkfawn", "fawn", "argent", 
			 "buttercream", "atlas", "heavenly", "pearl", "ruffian", "sphinx", "darkvanilla", "deepfawn", "hazelnut", 
			 "mongoose", "cameo", "finch", "aardwolf", "ammonite", "asiatic", "esker", "fossil", "guardian", "hallowed", 
			 "jackal", "mushroom", "pecora", "ragdoll", "smog", "darkbrown", "liver", "silver", "flint", "platinum", 
			 "basalt", "dapplegray", "demiurge", "duat", "frostbitten", "incorporeal", "lilac", "majivu", "medal", 
			 "nephthys", "rhino", "dun", "steele", "sterling", "maltese", "cocoa", "desolate", "arctic", "aufeis", 
			 "bluepoinsettia", "cottoncandy", "cloudburst", "ennead", "hematite", "hoarfrost", "leonid", "moonstone", 
			 "murk", "rime", "sidereal", "zombie"],
	light: ["dovegray", "dusty", "rosybrown", "silvergray", "chartreux", "snowpard", "glacial", "kunzite", "mistletoe", 
			"opal", "pulsar", "skyward", "snowflake", "soul", "stratosphere", "albino", "birch", "eggshell", "isabel", 
			"white", "aspen", "clearwhite", "willow", "ashen", "frost", "cairngorm", "celsian", "glass", "gleam", "khnum", 
			"opalescent", "phantom", "waterhyacinth", "almond", "antler", "vanilla", "buff", "tusk", "aether", 
			"cherryblossom", "eggnog", "ethereal", "horizon", "howlite", "ivory", "nautilus", "skeletal", "apricot",
			"beige", "creamlighter", "lightcream", "buttermilk", "latte", "teardrop", "alabaster", "citron", "solaris", 
			"bisquit", "bone", "sunglow", "wheaten", "champagne", "powder", "angelic", "citrine", "haliotis", "horus",
			"maat", "nudar", "peach", "triumph", "bisque", "lemon", "lightgolden", "linen", "zer", "zivar", "sunshine", 
			"sulphur", "sunkissed", "festive", "harvestmoon", "hexaplex", "marula", "ukame", "copper", "palomino", "sorrel", 
			"tawny", "rufous", "fiery", "maroon", "taupe", "ancestral", "astral", "azalea", "bandit", "blazing", "dawn", 
			"drupa", "flamingo", "fuchsia", "iris", "lotus", "nefer", "sunrise", "sutekh", "cedar", "cremello", "fallow", 
			"sandy", "wildrose", "cinnabar", "sapela", "ardor", "decennial", "orchid", "rainbow", "rosepink", "serruria", 
			"ubaste"],
}

const rarity = {
	common: ["almond", "antler", "apricot", "auburn", "beige", "birch", "bisque", "bisquit", "black", "blonde", "bone", 
			 "brass", "bronze", "brown", "camel", "caramel", "cedar", "chestnut", "chocolate", "copper", "cream", 
			 "creamdarker", "creamlighter", "cremello", "darkbrown", "darkfawn", "darkgolden", "darkvanilla", "deepfawn", 
			 "deira", "dikela", "doubloon", "dovegray", "ducat", "dun", "dusty", "dustyrose", "eggshell", "fallow",
			 "fawn", "ginger", "gray", "hazelnut", "henna", "isabel", "jacinthe", "jet", "khaki", "lbino", "lemon", 
			 "lightcream", "lightgolden", "linen", "liver", "locust", "luteo", "mahogany", "mauve", "mediumgolden", 
			 "mongoose", "mulberry", "oatmeal", "obsidian", "ochre", "palomino", "pecan", "persimmon", "pewter", 
			 "redwood", "rosybrown", "ruddy", "rust", "saffron", "sandy", "savannah", "sienna", "silver", "silvergray", 
			 "sorrel", "steele", "sterling", "sundust", "sunflower", "sunglow", "tan", "tawny", "titanium", "vandal", 
			 "vanilla", "wheaten", "white", "wildrose", "zarafshan", "zarasa", "zarbanu", "zarin", "zer", "zivar"],
	uncommon: ["aspen", "buttermilk", "butternut", "clearwhite", "korat", "maltese", "onyx", "rhubarb", "rufous", 
			   "russet", "sunshine", "topaz", "willow", "xanthic", "gunmetalgray"],
	rare: ["acacia", "amber", "anjeer", "argent", "ashen", "buff", "buttercream", "cameo", "cassis", "champagne", 
		   "chartreux", "cimmerian", "cinnabar", "cocoa", "dandelion", "desolate", "dinar", "ebony", "fiery", "finch", 
		   "flaxen", "flint", "frost", "fulvous", "goldenrod", "goridhe", "honey", "latte", "maroon", "nacarat", "noctis", 
		   "platinum", "powder", "prune", "red", "sapela", "scallop", "senegal", "shedua", "slate", "snowpard", "soot", 
		   "sulphur", "sunkissed", "taupe", "teardrop", "tusk", "udara", "umber"],
	special: ["aardwolf", "abyssinian", "aether", "ailurus", "alabaster", "ambrosia", "ammonite", "ancestral", "angelic", 
			  "ankh", "anubis", "arabica", "arctic", "ardor", "asali", "asiatic", "astral", "ater", "atlas", "aufeis", 
			  "augur", "azalea", "bandit", "basalt", "bast", "beet", "blackrose", "blazing", "bloodbourne", "bloodmoon", 
			  "bloodstone", "blue poinsettia", "blushrose", "brimstone", "bushveld", "cabochon", "cairngorm", "celestial", 
			  "celsian", "chaos", "chatoyant", "cherryblossom", "citrine", "citron", "cloudburst", "constellation", 
			  "cottoncandy", "cretaceous", "damu", "dapplegray", "dawn", "decennial", "demiurge", "demonic", "deshret", 
			  "dhahabi", "divine", "drupa", "duat", "eggnog", "elysian", "ember", "ennead", "esker", "ethereal", 
			  "festive", "flamingo", "fossil", "frostbitten", "fuchsia", "ganache", "gilded", "glacial", "glass", "gleam", 
			  "green", "gregarious", "grullo", "guardian", "haliotis", "hallowed", "harbinger", "haruspex", "harvestmoon", 
			  "haunted", "haze", "heavenly", "heh", "hellebore", "hematite", "hexaplex", "hibiscus", "hirola", "hoarfrost", 
			  "horizon", "horus", "howlite", "hyena", "ice", "incense", "incorporeal", "inferno", "inpu", "interstellar", 
			  "iris", "ivory", "jacana", "jackal", "jellyfish", "khnum", "kimanjano", "kunzite", "labradorite", "leonid", 
			  "lilac", "lotus", "maat", "madagascar", "majivu", "manakbir", "mandarin", "manticore", "marula", "maziwa", 
			  "medal", "merlot", "meteorite", "mistletoe", "mobola", "moonstone", "mossagate", "mudstone", "mummy", 
			  "murk", "mushroom", "nacre", "nadir", "nautilus", "nefer", "nephthys", "nether", "nomad", "nudar", "nun", 
			  "nuummite", "ogdoad", "olive", "opal", "opalescent", "orchid", "ornament", "outlaw", "parhelion", "peach", 
			  "pearl", "pecora", "penumbra", "phantom", "plague", "prismatic", "progenitor", "protea", "protostar", 
			  "przewalski", "pulsar", "qahir", "ra", "ragdoll", "rainbow", "reindeer", "rhino", "rhodonite", "rime", 
			  "ripe", "rosegold", "rosepink", "roughruby", "ruffian", "sahara", "sarcophagus", "scoundrel", "seer", "sepia", 
			  "sepulture", "serruria", "seth", "sha", "shard", "sidereal", "skeletal", "skyward", "smog", "snowflake", 
			  "solaris", "soul", "spectre", "sphinx", "squall", "stratosphere", "styx", "sunrise", "sunset", "sunspot", 
			  "supernal", "sutekh", "swarm", "temporal", "thoth", "triumph", "trophy", "ubaste", "ukame", "unholy", 
			  "vagabond", "velvet", "victor", "waterhyacinth", "wepwawet", "wicked", "windfall", "wine", "witch", "wither", 
			  "zloto", "zombie"],
}

const type = {
	basechanger: ["albino", "almond", "antler", "apricot", "aspen", "auburn", "beige", "birch", "bisque", "bisquit", 
				  "black", "blonde", "bone", "brass", "bronze", "brown", "buttermilk", "butternut", "camel", "caramel", 
				  "cedar", "chestnut", "chocolate", "clearwhite", "copper", "cream", "creamdarker", "creamlighter", 
				  "cremello", "darkbrown", "darkfawn", "darkgolden", "darkvanilla", "deepfawn", "deira", "dikela", 
				  "doubloon", "dovegray", "ducat", "dun", "dusty", "dustyrose", "eggshell", "fallow", "fawn", "ginger", 
				  "gray", "gunmetalgray", "hazelnut", "henna", "isabel", "jacinthe", "jet", "khaki", "korat", "lemon", 
				  "lightcream", "lightgolden", "linen", "liver", "luteo", "mahogany", "maltese", "mauve", "mediumgolden", 
				  "mongoose", "mulberry", "oatmeal", "obsidian", "ochre", "onyx", "palomino", "pecan", "persimmon", "pewter", 
				  "redwood", "rhubarb", "rosybrown", "ruddy", "rufous", "russet", "rust", "saffron", "sandy", "savannah", 
				  "sienna", "silver", "silvergray", "sorrel", "steele", "sterling", "sundust", "sunflower", "sunglow", 
				  "sunshine", "tan", "tawny", "titanium", "topaz", "vandal", "vanilla", "wheaten", "white", "wildrose", 
				  "willow", "xanthic", "zarafshan", "zarasa", "zarbanu", "zarin", "zer", "zivar"],
	applicator: ["aardwolf", "alabaster", "ammonite", "ancestral", "angelic", "ankh", "anubis", "arctic", "ardor", 
				 "astral", "atlas", "aufeis", "augur", "azalea", "bast", "blazing", "bloodbourne", "bloodmoon", 
				 "bloodstone", "bluepoinsettia", "blushrose", "brimstone", "cabochon", "chaos", "chatoyant", 
				 "cherryblossom", "citron", "cottoncandy", "cretaceous", "dapplegray", "decennial", "demiurge", 
				 "demonic", "deshret", "divine", "drupa", "duat", "eggnog", "ethereal", "festive", "flamingo", "fossil", 
				 "frostbitten", "fuchsia", "glacial", "glass", "green", "gregarious", "grullo", "guardian", "haliotis",
				 "hallowed", "harbinger", "haruspex", "harvestmoon", "haunted", "heavenly", "hematite", "hibiscus", 
				 "hirola", "horus", "howlite", "hyena", "ice", "incense", "incorporeal", "inferno", "inpu", "interstellar", 
				 "ivory", "jacana", "jackal", "khnum", "kunzite", "labradorite", "locust", "lotus", "maat", "manakbir", 
				 "manticore", "marula", "medal", "merlot", "meteorite", "moonstone", "mossagate", "mummy", "murk", "nacre", 
				 "nautilus", "nefer", "nephthys", "nuummite", "opal", "ornament", "parhelion", "peach", "penumbra",
				 "phantom", "protea", "przewalski", "ragdoll", "rainbow", "reindeer", "rhino", "rhodonite", "rosepink", 
				 "roughruby", "sarcophagus", "seer", "sepulture", "seth", "sha", "shard", "skeletal", "solaris", "spectre", 
				 "supernal", "sutekh", "swarm", "thoth", "triumph", "trophy", "ubaste", "unholy", "velvet", "victor", 
				 "waterhyacinth", "wepwawet", "wicked", "windfall", "zombie"],
	piety: ["progenitor"],
	breedonly: ["abyssinian", "acacia", "amber", "ambrosia", "anjeer", "argent", "asali", "ashen", "bandit", "beet", "buff", 
				"bushveld", "buttercream", "cameo", "cassis", "celestial", "champagne", "chartreux", "cimmerian", "cinnabar", 
				"cocoa", "damu", "dandelion", "dawn", "desolate", "dhahabi", "dinar", "ebony", "fiery", "finch", "flaxen", 
				"flint", "frost", "fulvous", "goldenrod", "goridhe", "haze", "honey", "iris", "jellyfish", "latte", "leonid", 
				"lilac", "maroon", "maziwa", "mobola", "mushroom", "nacarat", "noctis", "nomad", "nudar", "opalescent", "orchid",
				"outlaw", "pearl", "pecora", "platinum", "powder", "prismatic", "protostar", "prune", "red", "ripe", "ruffian",
				"sahara", "sapela", "scallop", "scoundrel", "senegal", "sepia", "shedua", "sidereal", "skyward", "slate", 
				"snowpard", "soot", "stratosphere", "sulphur", "sunkissed", "sunrise", "sunset", "sunspot", "taupe", 
				"teardrop", "tusk", "udara", "ukame", "umber", "vagabond", "wine", "wither"],
	combo: ["aether", "ailurus", "arabica", "asiatic", "ater", "basalt", "black rose", "cairngorm", "celsian", "citrine", 
			"cloudburst", "constellation", "elysian", "ember", "ennead", "esker", "ganache", "gilded", "gleam", "heh", 
			"hellebore", "hexaplex", "hoarfrost", "horizon", "madagascar", "majivu", "mistletoe", "mudstone", "nadir", 
			"nether", "nun", "ogdoad", "olive", "plague", "pulsar", "qahir", "ra", "rime", "rose gold", "serruria", "smog", 
			"snowflake", "soul", "sphinx", "squall", "styx", "temporal", "witch", "zloto"],
	hybrid: [ "mandarin", "kimanjano"],
}
