const colour = {
	black: ["Albino", "Arctic", "Aufeis", "Augur", "Basalt", "Birch", "Blue Poinsettia", "Celestial", "Celsian", "Chartreux", 
					"Chestnut", "Cocoa", "Cloudburst", "Constellation", "Demiurge", "Dapple Gray", "Divine", "Dove Gray", "Dun", "Duat", 
					"Ebony", "Ennead", "Elysian", "Frost", "Frostbitten", "Glass", "Glacial", "Gleam", "Gunmetal Gray", "Harbinger", 
					"Haruspex", "Haze", "Heh", "Hematite", "Ice", "Incense", "Incorporeal", "Interstellar", "Isabel", "Jet", "Khnum", 
					"Korat", "Kunzite", "Leonid", "Lilac", "Maltese", "Majivu", "Medal", "Moonstone", "Murk", "Nadir", "Nephthys", 
					"Noctis", "Nuummite", "Nun", "Obsidian", "Onyx", "Opal", "Opalescent", "Penumbra", "Platinum", "Pulsar", "Ra", "Rhino", 
					"Rime", "Rosy Brown", "Shard", "Silver", "Silver Gray", "Skyward", "Snowflake", "Snowpard", "Soul", "Steele", "Styx", 
					"Titanium", "Vandal", "Velvet", "Water Hyacinth", "White", "Witch"],
	cream: ["Aardwolf", "Aether", "Alabaster", "Almond", "Ammonite", "Amber", "Apricot", "Antler", "Arabica", "Argent", "Atlas", 
					"Beige", "Buff", "Buttercream", "Buttermilk", "Camel", "Cameo", "Caramel", "Citrine", "Cherry Blossom", 
					"Cream", "Cream Darker", "Cream Lighter", "Dark Fawn", "Dark Vanilla", "Dusty Rose", "Esker", "Eggnog", "Ethereal", 
					"Finch", "Flaxen", "Fossil", "Fawn", "Guardian", "Hallowed", "Hellebore", "Heavenly", "Horizon", "Howlite", "Ivory", 
					"Jackal", "Khaki", "Latte", "Moss Agate", "Meteorite", "Mummy", "Nacre", "Nautilus", "Nomad", "Olive", "Outlaw", 
					"Parhelion", "Pecora", "Pecan", "Pearl", "Persimmon", "Qahir", "Ragdoll", "Reindeer", "Ruffian", "Russet", "Savannah", 
					"Seer", "Senegal", "Skeletal", "Sphinx", "Solaris", "Supernal", "Smog", "Tan", "Tusk", "Vanilla", "Vagabond"],
	golden: ["Abyssinian", "Ailurus", "Angelica", "Anubis", "Asali", "Bast", "Bisque", "Bisquit", "Bone", "Bushveld", "Cabochon", 
					 "Champagne", "Chatoyant", "Citrine", "Cretaceous", "Damu", "Dandelion", "Deira", "Dinar", "Doubloon", "Ducat", "Ember", 
					 "Festive", "Ganache", "Gilded", "Goridhe", "Green", "Gregarious", "Haliotis", "Harvest Moon", "Hexaplex", "Horus", 
					 "Honey", "Hirola", "Jacinthe", "Kimanjano", "Labradorite", "Lemon", "Light Golden", "Linen", "Luteo", "Maat", "Mandarin", 
					 "Marula", "Medium Golden", "Mobola", "Mudstone", "Nacarat", "Nudar", "Oatmeal", "Ochre", "Ornament", "Peach", "Powder", 
					 "Protostar", "Ripe", "Saffron", "Sahara", "Sarcoophagus", "Sepulture", "Sunkissed", "Sunflower", "Sunlight", "Sundust", 
					 "Sunshine", "Swarm", "Sulphur", "Topaz", "Trophy", "Udara", "Ukame", "Victor", "Wheaten", "Wither", "Xanthic", "Zarasa", 
					 "Zarin", "Zarbanu", "Zarafshan", "Zer", "Zivar", "Zloto"],
	red: ["Acacia", "Ambrosia", "Ancestral", "Anjeer", "Ankh", "Ater", "Ardor", "Astral", "Azalea", "Bandit", "Beet", "Blazing", 
				"Blush Rose", "Blood Moon", "Bloodbourne", "Bloodstone", "Black Rose", "Brass", "Brimstone", "Bronze", "Brown", "Cassis", 
				"Cedar", "Chocolate", "Cinnabar", "Copper", "Cremello", "Dawn", "Decennial", "Demonic", "Deshret", "Drupa", "Fallow", "Fiery", 
				"Flamingo", "Fuchsia", "Ginger", "Haunted", "Henna", "Hibiscus", "Inferno", "Iris", "Locust", "Lotus", "Madagascar", "Mahogany", 
				"Manakbir", "Manticore", "Maroon", "Mauve", "Merlot", "Mulberry", "Nefer", "Nether", "Ogdoad", "Orchid", "Palomino", "Plague", 
				"Prismatic", "Protea", "Progenitor", "Red", "Rainbow", "Rhodonite", "Rhubarb", "Rose Gold", "Rose Pink", "Rough Ruby", "Rufous", 
				"Rust", "Sandy", "Sapela", "Sassafras", "Scallop", "Scoundrel", "Serruria", "Sepia", "Seth", "Shedua", "Sorrel", "Squall", 
				"Sunrise", "Sunset", "Sutekh", "Taupe", "Tawny", "Temporal", "Ubaste", "Umber", "Unholy", "Wepwawet", "Windfall", "Wild Rose", 
				"Wine", "Wicked"]
}
