const type = {
	eyechanger: ["amber", "aqua", "black", "blue", "bronze", "brown", "cognac", "crimson", "crystal", "cucumber", "denim", 
				 "earth", "emerald", "green", "grey", "hazel", "heteroblackwhite", "heterobluebrown", "heterobluegreen", 
				 "heterobluegrey", "heterobrownblue", "heterogreenblue", "heterogreenyellow", "heterogreyblue", "heterojetred", 
				 "heteroredjet", "heterowhiteblack", "heteroyellowgreen", "ice", "jade", "jet", "malachite", "mint", "olive", 
				 "paradise", "peach", "pink", "red", "saffron", "sage", "sandy", "sapphire", "seafoam", "silver", "sinoper", 
				 "smoke", "sodalite", "storm", "sunburst", "sunset", "sunstone", "tan", "tyrian", "white", "yellow"],
	applicator: ["amethyst", "aphoph", "arid", "bismuth", "carnelian", "celestite", "chaos", "cloudy", "confetti", 
               "crepuscular", "demon", "dioptase", "doom", "drongo", "drowned", "eldritch", "fiercegreen", "fiercered", 
               "fireopal", "fog", "garnet", "indigo", "intenseblood", "intensegold", "intenseheat", "intensesalt", "jasper", 
               "lavender", "lehsunia", "medusa", "midnight", "mist", "nebula", "omen", "opal", "peacock", "peridot", "reptile", 
               "richat", "sign", "snake", "starruby", "struthio", "tanzanite", "vile", "violet", "zoisite"],
	piety: ["scarab"],
	breedonly: ["aegean", "albinoid", "apricot", "axion", "banana", "blueiris", "burnish", "celadon", "ceramic", "chamotte", 
				"cherimoya", "clay", "coconut", "cordovan", "daisy", "dawn", "demiurge", "dove", "draconid", "dunt", "eglomise", 
				"epicene", "faience", "fern", "flax", "galaxy", "gazania", "gem", "glass", "glaze", "grape", "guava", 
				"herteroiceblue", "heteroblueice", "heterocucumbersaffron", "heterodenimjade", "heteroearthintensegold", 
				"heterointensegoldearth", "heterointensesaltmalachite", "heterojadedenim", "heteromalachiteintensesalt", 
				"heterosaffroncucumber", "hyacinth", "iris", "kiwifruit", "maneater", "maroon", "mire", "mosaic", "moss",
				"neutron", "ocean", "pearl", "phase", "porcelain", "preon", "primrose", "rose", "roseebony", "rosequartz", 
				"slate", "smalti", "starshine", "stellar", "sunglow", "terracotta", "terrazzo", "tessera", "vicious"],
	combo: ["aquamarine", "birman", "calathea", "coffee", "cosmic", "dusk", "euphorbia", "gliese", "goldenshine", "pine", 
			"sectoralamberice", "sectoralapricotsapphire", "sectoralaquagrape", "sectoralbrownblue", "sectoralcolorbomb", 
			"sectoralcrystalfireopal", "sectoralcrystallavender", "sectoraldraconidreptile", "sectoralgreenblue", 
			"sectoralicegreen", "sectoralpinkice", "sectoralpinkmint", "sectoralpinkviolet", "sectoralredjet", 
			"sectoralsapphirealbinoid", "sectoraltranquility", "sectoraltyrianindigo", "sectoralyellowgreen", "shamal", 
			"spacetime", "void", "wistful"],
}
