const shape = {
	manechanger: ["barbary", "crested", "heavy", "katanga", "normal", "razor", "regal", "regent", "scarce", "sideburn", 
				  "sideward", "thick", "transvaal", "tufted", "wavy"],
	applicator: ["blade", "diabolic", "hellraiser", "incubus"],
	breedonly: ["pariah", "savage", "tsavo"],
	combo: ["royal"],
}

const colour = {
	manecolourchanger: ["almond", "auburn", "beige", "black", "blonde", "blue", "brass", "brown", "camel", "caramel", 
						"chestnut", "chocolate", "copper", "creamdarker", "creamlighter", "cream", "cremello", 
						"darkbrown", "darkfawn", "darkgolden", "darkvanilla", "deepfawn", "deira", "dikela", "doubloon", 
						"dovegray", "ducat", "dun", "dustyrose", "dusty", "eggshell", "fallow", "fawn", "ginger", "gray", 
						"gunmetalgray", "hazelnut", "henna", "isabel", "jacinthe", "jet", "khaki", "korat", "lightcream", 
						"lightgolden", "liver", "luteo", "mahogany", "maltese", "mauve", "mediumgolden", "mongoose", 
						"mulberry", "obsidian", "ochre", "onyx", "palomino", "pecan", "persimmon", "pewter", "red", 
						"redwood", "rosybrown", "ruddy", "rufous", "russet", "rust", "saffron", "sandy", "savannah", 
						"sienna", "silvergray", "silver", "sorrel", "steele", "sterling", "sundust", "sunflower", 
						"sunglow", "tan", "tawny", "titanium", "vandal", "vanilla", "walnut", "white", "wildrose", 
						"willow", "zarafshan", "zarasa", "zarbanu", "zarin", "zer", "zivar"],
	applicator: ["ammonite", "ancestral", "angelic", "arctic", "ardor", "astral", "atlas", "aufeis", "augur", "azalea", 
				 "blazing", "bloodbath", "bloodbourne", "bloodmoon", "bloodstone", "bluepoinsettia", "blushrose", 
				 "brimstone", "celestial", "chatoyant", "cherryblossom", "cloudburst", "cottoncandy", "cretaceous", 
				 "demonic", "divine", "eggnog", "ethereal", "flamingo", "fossil", "frostbitten", "fuchsia", "glacial", 
				 "green", "gregarious", "guardian", "hallowed", "harvestmoon", "haunted", "heavenly", "hematite", 
				 "hibiscus", "hirola", "howlite", "hyena", "ice", "incorporeal", "infernal", "ivory", "jacana", 
				 "kunzite", "labradorite", "manakbir", "maroon", "merlot", "meteorite", "moonstone", "mossagate", 
				 "murk", "nacre", "noctis", "nuummite", "opal", "parhelion", "peach", "penumbra", "phantom", "przewalski",
				 "ragdoll", "reindeer", "rhino", "rhodonite", "rosepink", "roughruby", "seer", "sepulture", "shard", 
				 "sidereal", "skyward", "spectre", "styx", "sunrise", "sunset", "supernal", "unholy", "waterhyacinth", 
				 "wicked", "windfall", "zombie"],
	piety: ["fennec", "progenitor"],
	breedonly: [ "abyssinian", "algae", "amber", "anjeer", "ashen", "beet", "briar", "cameo", "champagne", "chartreux", 
				"cimmerian", "cinnabar", "clay", "cocoa", "copal", "damu", "dinar", "ebony", "fiery", "flaxen", "flint", 
				"fulvous", "goldenrod", "honey", "lilac", "Marigold", "mushroom", "nacarat", "nudar", "orchid", "pearl", 
				"pistachio", "platinum", "prune", "ripe", "ruffian", "sahara", "scoundrel", "seal", "sepia", "shedua", 
				"slate", "spice", "sunspot", "taupe", "tusk", "ukame", "umber", "wine"],
	combo: ["aether", "basalt", "cairngorm", "citrine", "elysian", "madagascar", "nether", "qahir", "serruria", "soul"],
}
